/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas_banco;

/**
 *
 * @author fvarg
 */
public class Informacion_bancaria extends javax.swing.JFrame {

    /**
     * Creates new form Informacion_bancaria
     */
    public Informacion_bancaria() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contenedor1 = new javax.swing.JPanel();
        titulo_cuentas1 = new javax.swing.JLabel();
        titulo_cuenta1 = new javax.swing.JLabel();
        titulo_cuenta2 = new javax.swing.JLabel();
        titulo_cuenta3 = new javax.swing.JLabel();
        saldo1 = new javax.swing.JLabel();
        saldo2 = new javax.swing.JLabel();
        saldo3 = new javax.swing.JLabel();
        contenedor2 = new javax.swing.JPanel();
        titulo_cuentas2 = new javax.swing.JLabel();
        img_tarjeta1 = new javax.swing.JLabel();
        img_tarjeta2 = new javax.swing.JLabel();
        img_tarjeta3 = new javax.swing.JLabel();
        titulo_cuentas3 = new javax.swing.JLabel();
        titulo_cuentas4 = new javax.swing.JLabel();
        titulo_cuentas5 = new javax.swing.JLabel();
        Identificador_tarjeta3 = new javax.swing.JLabel();
        Identificador_tarjeta2 = new javax.swing.JLabel();
        Identificador_tarjeta1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(159, 100, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 5, 10, 5, new java.awt.Color(0, 0, 0)));

        contenedor1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_cuentas1.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        titulo_cuentas1.setText("Cuentas en pesos");
        contenedor1.add(titulo_cuentas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 128, -1));

        titulo_cuenta1.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        titulo_cuenta1.setText("Cuenta 1");
        contenedor1.add(titulo_cuenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        titulo_cuenta2.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        titulo_cuenta2.setText("Cuenta 2");
        contenedor1.add(titulo_cuenta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        titulo_cuenta3.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        titulo_cuenta3.setText("Cuenta 3");
        contenedor1.add(titulo_cuenta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        saldo1.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        saldo1.setText("$ 235.24");
        contenedor1.add(saldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 52, -1));

        saldo2.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        saldo2.setText("$ 2.15");
        contenedor1.add(saldo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 52, -1));

        saldo3.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        saldo3.setText("$ 648.54");
        contenedor1.add(saldo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 52, -1));

        titulo_cuentas2.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        titulo_cuentas2.setText("Tarjetas");

        img_tarjeta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tarjeta-de-credito.png"))); // NOI18N

        img_tarjeta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tarjeta-de-credito.png"))); // NOI18N

        img_tarjeta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tarjeta-de-credito.png"))); // NOI18N

        titulo_cuentas3.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        titulo_cuentas3.setText("Visa Debito");

        titulo_cuentas4.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        titulo_cuentas4.setText("MasterCard");

        titulo_cuentas5.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        titulo_cuentas5.setText("Visa Credito");

        Identificador_tarjeta3.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        Identificador_tarjeta3.setText("• 3078");

        Identificador_tarjeta2.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        Identificador_tarjeta2.setText("•1684");

        Identificador_tarjeta1.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        Identificador_tarjeta1.setText("•4861");

        javax.swing.GroupLayout contenedor2Layout = new javax.swing.GroupLayout(contenedor2);
        contenedor2.setLayout(contenedor2Layout);
        contenedor2Layout.setHorizontalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo_cuentas2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contenedor2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img_tarjeta2)
                            .addComponent(img_tarjeta1)
                            .addComponent(titulo_cuentas4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo_cuentas3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(img_tarjeta3)
                            .addComponent(titulo_cuentas5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Identificador_tarjeta3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Identificador_tarjeta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Identificador_tarjeta2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenedor2Layout.setVerticalGroup(
            contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo_cuentas2)
                .addGap(14, 14, 14)
                .addComponent(titulo_cuentas3)
                .addGroup(contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedor2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img_tarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedor2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Identificador_tarjeta1)))
                .addGap(21, 21, 21)
                .addComponent(titulo_cuentas4)
                .addGroup(contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedor2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img_tarjeta2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedor2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Identificador_tarjeta2)))
                .addGroup(contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedor2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(titulo_cuentas5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(img_tarjeta3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedor2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Identificador_tarjeta3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(39, 39, 39))
        );

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/atras.png"))); // NOI18N
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(contenedor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(contenedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        Home abrir = new Home();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_bancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_bancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_bancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_bancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_bancaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Identificador_tarjeta1;
    private javax.swing.JLabel Identificador_tarjeta2;
    private javax.swing.JLabel Identificador_tarjeta3;
    private javax.swing.JButton btn1;
    private javax.swing.JPanel contenedor1;
    private javax.swing.JPanel contenedor2;
    private javax.swing.JLabel img_tarjeta1;
    private javax.swing.JLabel img_tarjeta2;
    private javax.swing.JLabel img_tarjeta3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel saldo1;
    private javax.swing.JLabel saldo2;
    private javax.swing.JLabel saldo3;
    private javax.swing.JLabel titulo_cuenta1;
    private javax.swing.JLabel titulo_cuenta2;
    private javax.swing.JLabel titulo_cuenta3;
    private javax.swing.JLabel titulo_cuentas1;
    private javax.swing.JLabel titulo_cuentas2;
    private javax.swing.JLabel titulo_cuentas3;
    private javax.swing.JLabel titulo_cuentas4;
    private javax.swing.JLabel titulo_cuentas5;
    // End of variables declaration//GEN-END:variables
}
